name = "Наш сервер"
author = "danilakanakov-ops"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76e908afaecdd28d3314c189e069025109d1210d618d4d659caccf11e9cb3771"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
