name = "Наш сервер"
author = "danilakanakov-ops"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08a2659e289fa8f8a11d62920a45432b240c54c8690d3dd88b80580347e5c86d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
